basePath: /
host: localhost:8080
info:
  contact: {}
  description: Una app de red social simple de chateo
  title: ChatLanGO API
  version: "1.0"
paths:
  /auth/register:
    post:
      description: Registro de nuevos usuarios
      produces:
      - application/json
      responses: {}
      summary: Endpoint register
      tags:
      - Register
  /test/:
    get:
      description: Devuelve un mensaje simple para verificar el funcionamiento del
        servidor.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Endpoint de prueba validada
      tags:
      - Test
swagger: "2.0"
